#%RAML 1.0
types:
  major-mahaveer:
    properties:
      id:
        example: "2482"
        type: string
      name:
        example: Kartik Kocchar
        type: string
      email:
        example: kartik_kocchar@rutherford.io
        type: string
      gender:
        example: female
        type: string
      status:
        example: inactive
        type: string
  NewDataTyp:
    type: object
title: Major-mahaveer
mediaType:
  - application/json
protocols:
  - HTTP
/milestone-2:
  get:
    responses:
      "200": {}
/milestone1:
  get:
    responses:
      "200":
        body:
          type: major-mahaveer
